---
- hosts: local
  become_user: litleleprikon
  become: True

  vars:
    - dropletname: manager
  
  roles:
    - DrMegahertz.cloudflare

  tasks:

  - debug: msg="User name {{ansible_user_id}}"

  - name: ensure ssh key exists
    user: >
      name={{ ansible_user_id }}
      generate_ssh_key=yes
      ssh_key_file="~/.ssh/chat_id_rsa"

  - name: ensure key exists at DigitalOcean
    digital_ocean: >
      state=present
      command=ssh
      name=my_ssh_key
      ssh_pub_key={{ lookup('file', '~/.ssh/chat_id_rsa.pub') }}
    register: my_ssh_key

  - debug: msg="ssh {{my_ssh_key}}"

  - debug: msg="Droplet name {{dropletname}}"

  - name: ensure droplet one exists
    digital_ocean: >
      state=present
      command=droplet
      name={{dropletname}}
      size_id=512mb
      region_id=sgp1
      image_id=coreos-stable
      ipv6=no
      ssh_key_ids={{ my_ssh_key.ssh_key.id }}
    register: created_droplet

  - debug: msg="Droplet {{ created_droplet }}"

  - debug: msg="IP is {{ created_droplet.droplet.ip_address }}"

  - name: Add DNS record
    cloudflare_domain: >
        state=present
        name=manager.chat
        zone=litleleprikon.me
        type=A
        content={{ created_droplet.droplet.ip_address }}

  - name: Add host to groupname
    add_host:
      hostname: "{{ created_droplet.droplet.ip_address }}"
      ansible_ssh_private_key_file: ~/.ssh/chat_id_rsa
      groupname: new_instances

- hosts: new_instances

  remote_user: core
  connection: ssh
  become: True
  become_user: core
  
  tasks:
  - name: New instance configuration
  - debug: msg="IP is {{ inventory_hostname }}"

  tasks:
    - name: Initialize swarm cluster
      shell: >
        docker swarm init --advertise-addr="{{created_droplet.droplet.ip_address}}:2377"
